arb-dir: lib/src/common/localization/l10n
template-arb-file: app_en.arb
output-localization-file: vaultiq_localizations.dart
output-class: VaultiqLocalization
nullable-getter: false
synthetic-package: false
output-dir: lib/src/common/localization/flutter_gen
supported-languages:
  - en
  - tr
  - ru
  - it