name: Build VaultiQ

on:
  push:
    branches: [dev, master]
    paths:
      - "lib/**"
  pull_request:
    branches: [dev, master]
    paths:
      - "lib/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install latest Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
          cache: true

      - name: Initialize dependencies
        run: |
          flutter pub get

      - name: Check dependencies
        run: |
          flutter pub outdated

      - name: Analyze code
        run: |
          flutter analyze

      - name: Run tests
        run: |
          flutter test

      - name: Build Android APK
        run: |
          flutter build apk

